apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice
  labels:
    app: searchservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      name: searchservice
      labels:
        app: searchservice
    spec:
      containers:
        - name: searchservice
          image: mattan41/chatgut:v1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8009
              protocol: TCP
      restartPolicy: Always