apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchservice
  labels:
    app: searchservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchservice
  template:
    metadata:
      name: searchservice
      labels:
        app: searchservice
    spec:
      containers:
        - name: searchservice
          image: mattan41/chatgut:v1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8009
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-service"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ROCKET_RABBIT_HOST
              value: "rabbitmq-app"
            - name: ROCKET_RABBIT_PORT
              value: "5672"
      restartPolicy: Always