apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
#          volumeMounts:
#            - name: rabbitmq-data
#              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
              - key: enabled_plugins
                path: enabled_plugins
#        - name: rabbitmq-data
#          persistentVolumeClaim:
#            claimName: rabbitmq-pv-claim
#      initContainers:
#        - name: enable-management-plugin
#          image: rabbitmq:3-management-alpine
#          command: [ "rabbitmq-plugins", "enable", "rabbitmq_management" ]